// NOTE: SIMPLEST WAY
// NOTE: FOR EXAMPLE THIS FUNCTION WILL BE HER AND YOU WILL CAL THESE FUNCTION INSIDE THE EXACT HOOK YOU WILL USE FOR THIS SERVICE
const exampleService = () => {};

export default exampleService;
